require 'elasticsearch'
require 'elasticsearch/model'
require 'elasticsearch/persistence'
require "insuggest/discount"
require "insuggest/depreciation"
require "insuggest/gcv/discount"
require "insuggest/gcv/depreciation"
require "insuggest/travel"
require "insuggest/tp_vendor"
require "insuggest/idv"
require "insuggest/version"
